#!/usr/bin/env python3
"""
gen_download_batch.py — Generate the one-shot download script for scoped
documents that need text (step 3 of the workplan).

Covers:
  - every scoped doc with text_source=download-needed and a direct-fetchable URL
  - the three scanned-act replacements (Irish Statute Book HTML full text)
Landing-page URLs that need a human to pick the PDF go to MANUAL_DOWNLOADS.md.

Outputs (in ../corpus_build/):
  fetch_corpus_texts.sh   run once on the Mac:  bash fetch_corpus_texts.sh
  MANUAL_DOWNLOADS.md     the handful needing a manual save-as
"""

import csv
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent / "corpus_build"
OUT.mkdir(exist_ok=True)
(OUT / "downloads").mkdir(exist_ok=True)

# scanned-PDF replacements: fetch full text as eISB HTML
EXTRACTION_FIXES = {
    "IE_MONUMENTS_ACT_1930": "https://www.irishstatutebook.ie/eli/1930/act/2/enacted/en/html",
    "IE_COAST_PROTECTION_ACT_1963": "https://www.irishstatutebook.ie/eli/1963/act/12/enacted/en/html",
    "IE_ARTERIAL_DRAINAGE_AMENDMENT_ACT_1995": "https://www.irishstatutebook.ie/eli/1995/act/14/enacted/en/html",
}


def is_direct(url: str) -> tuple[bool, str]:
    """(fetchable-by-curl, extension)"""
    u = url.lower()
    if u.endswith(".pdf") or "/pdf/?file=" in u or "revisedacts.lawreform.ie" in u and u.endswith("/pdf"):
        return True, "pdf"
    if "eur-lex.europa.eu" in u and "txt/pdf" in u:
        return True, "pdf"
    if "irishstatutebook.ie" in u:
        return True, "html"          # eISB pages are the full statutory text
    # hosts that reliably block curl -> route to manual save-as
    if any(h in u for h in ("npws.ie", "revisedacts.lawreform.ie", "coford.ie",
                            "epa.ie", "teagasc.ie", "waterwaysireland.org")):
        return False, ""
    if "assets.gov.ie" in u and u.endswith(".pdf"):
        return True, "pdf"
    return False, ""


def main():
    rows = list(csv.DictReader(open(HERE / "corpus_scope.csv", encoding="utf-8")))
    fetch, manual = [], []

    for r in rows:
        if r["include"] != "yes" or r["text_source"] != "download-needed":
            continue
        url = (r["source_url"] or "").strip()
        if not url:
            continue
        ok, ext = is_direct(url)
        if ok:
            fetch.append((r["id"], url, ext, r["title"]))
        else:
            manual.append((r["id"], url, r["title"]))

    for rid, url in EXTRACTION_FIXES.items():
        fetch.append((rid, url, "html", f"[extraction fix] {rid}"))

    lines = [
        "#!/bin/bash",
        "# One-shot corpus text fetch — generated by gen_download_batch.py",
        "# Usage:  bash fetch_corpus_texts.sh     (safe to re-run; skips existing files)",
        'cd "$(dirname "$0")/downloads" || exit 1',
        'UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"',
        "ok=0; fail=0; skip=0",
        "",
    ]
    for rid, url, ext, title in fetch:
        fn = f"{rid}.{ext}"
        lines += [
            f"# {title[:70]}",
            f'if [ -s "{fn}" ]; then echo "skip {fn}"; skip=$((skip+1)); else',
            f'  if curl -sL --fail --retry 2 -A "$UA" -o "{fn}" "{url}"; then',
            f'    echo "ok   {fn}"; ok=$((ok+1));',
            f'  else echo "FAIL {fn}"; fail=$((fail+1)); rm -f "{fn}"; fi',
            "  sleep 1",
            "fi",
        ]
    lines += [
        "",
        'echo ""',
        'echo "done: $ok fetched, $skip skipped (already present), $fail failed"',
        'echo "if any failed, check MANUAL_DOWNLOADS.md workflow for those too"',
    ]
    (OUT / "fetch_corpus_texts.sh").write_text("\n".join(lines), encoding="utf-8")

    md = ["# Manual downloads",
          "",
          "These URLs are landing pages — open each, download the document PDF, and save",
          "it into `corpus_build/downloads/` with exactly the filename shown.",
          ""]
    for rid, url, title in manual:
        md.append(f"- **`{rid}.pdf`** — {title}")
        md.append(f"  {url}")
    (OUT / "MANUAL_DOWNLOADS.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"fetch script: {len(fetch)} files ({len(EXTRACTION_FIXES)} extraction fixes included)")
    print(f"manual list:  {len(manual)} files")
    print(f"outputs in:   {OUT}")


if __name__ == "__main__":
    main()
